version: "3.9"
services:

    fluent-bit:
        image: grafana/fluent-bit-plugin-loki:latest
        container_name: fluent-bit
        environment:
            - LOKI_URL=http://loki:3100/loki/api/v1/push
        volumes:
            - ./FluentBit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
        ports:
            - "24224:24224"
            - "24224:24224/udp"

    app:
        container_name: flask-app
        build: ./Application/
        ports:
            - "5000:5000"
        volumes:
            - flask-app-vol:/Application
        logging:
            driver: fluentd
            options:
                fluentd-address: 0.0.0.0:24224
        depends_on: 
            - "fluent-bit"

    loki:
        image: grafana/loki:latest
        container_name: loki
        expose:
            - "3100"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
            - "3000:3000"
        environment:
            GF_RENDERING_SERVER_URL: http://renderer:8081/render
            GF_RENDERING_CALLBACK_URL: http://grafana:3000/
            GF_LOG_FILTERS: rendering:debug
        volumes:
            - grafana-vol:/var/lib/grafana

    renderer:
        image: grafana/grafana-image-renderer:latest
        container_name: grafana-image-renderer
        expose:
            - "8081"
        environment:
            ENABLE_METRICS: "true"
            
volumes:
    flask-app-vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/Application'

    grafana-vol:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '$PWD/Grafana'
